on:
  push:
    branches: "master"
  schedule:
    - cron: "0 0 * * *"
jobs:
  run-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Install modules
        run: npm install
      - name: Run script
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: node index.js $CONFIG